:Author: garroble
:Email:
:Date: 10/02/2025
:Revision: 1.0
:License: Public Domain

= Project: WatchWinder

A custom made Watch Winder based on Arduino Cloud and 3D printing.

== Step 1: Installation
Go to https://github.com/garroble/WatchWinder for more information.

== Step 2: Arduino Cloud setup.
Create the following Cloud Variables:
....
Things Setup
  ├── bool          cl_winder_status => Cloud status of the device to know if it is running.
  ├── CloudCounter  cl_winder_turns  => Number of complete turns done in an active period.
  ├── CloudSchedule ctrl_start_time  => Scheduler to setup the daily active period.
  └── bool          ctrl_switch      => Remote control on/off.
....

=== Folder structure

....
 Firmware                  => Arduino sketch folder
  ├── WatchWinderCloud.ino => main Arduino file
  ├── thingProperties.h    => header file for ArduinoIoTCloud
  ├── arduino_secrets.h    => header for WiFi SSID/PASS
  └── ReadMe.adoc          => this file
....

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
