// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCtrlStartTimeChange();
void onCtrlSwitchChange();

CloudCounter cl_winder_turns;
CloudSchedule ctrl_start_time;
bool cl_winder_status;
bool ctrl_switch;

void initProperties(){

  ArduinoCloud.addProperty(cl_winder_turns, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ctrl_start_time, READWRITE, ON_CHANGE, onCtrlStartTimeChange);
  ArduinoCloud.addProperty(cl_winder_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ctrl_switch, READWRITE, ON_CHANGE, onCtrlSwitchChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
